version: "1"
services:
  app:
    cantainer_name: app
    restart: always
    build: 
    ports:
      - "4000:4000"
    links:
      - mango
  mango:
    container_name: mango
    image: mango
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
      